### ISSUE TITLE
bullet_physics_test: build error because Git symlinks on Windows are flaky

### ISSUE THREAD

**Issue by DerTee** [michal-z/zig-gamedev#26]
Low priority, zig version 0.10.0-dev.625+e42b5e76b, Windows 10

I get a build error in bullet_physics_test (all other samples build & run fine):
```
> zig build
D:\tmp\zig-tests\zig-gamedev\samples\bullet_physics_test\build.zig:4:25: error: unable to load 'D:\tmp\zig-tests\zig-gamedev\samples\bullet_physics_test\libs\zbullet\build.zig': FileNotFound
const zbullet = @import("libs/zbullet/build.zig");
```

That's broken for me since 1c5c3438a668680062f68e739d4ad568e94bd66b  Added zbullet (wip).

I found out that it's a git + windows + directory symlink problem, because everything works fine if I delete the Git placeholder file `zig-gamedev\samples\bullet_physics_test\lib\zbullet` for the symlink and replace it with a Windows symlink using `mklink`.

This is unfortunate for an example because out of the box it will probably not work for a lot of Windows users, because you have to setup git and windows in a fairly specific way (see https://stackoverflow.com/questions/5917249/git-symlinks-in-windows).

It would be preferable to handle this in the zig.build file if possible. I tried and failed to do that by changing
`zig-gamedev\samples\bullet_physics_test\build.zig` in line 148-149:
```
    // old version that only works with symlinks
    // exe.addPackagePath("zbullet", "libs/zbullet/src/zbullet.zig");
    // @import("libs/zbullet/build.zig").link(b, exe);

    // use relative paths to avoid git symlink problems on windows
    exe.addPackagePath("zbullet", "../../../libs/zbullet/src/zbullet.zig");
    @import("../../../libs/zbullet/build.zig").link(b, exe);
    
    // results in this error:
    // .\build.zig:151:5: error: import of file outside package path: '../../libs/zbullet/build.zig'
    // @import("../../libs/zbullet/build.zig").link(b, exe);
    // ^
```

Is there maybe another solution, maybe using a git submodule for zbullet or something like that?

**Comment by michal-z** [comment]
Yeah, I was suspecting problems with symlinks. I will figure out something.
Many thanks for the report.

**Comment by michal-z** [comment]
This is now fixed.

**Comment by DerTee** [comment]
Awesome, thanks!
