### ISSUE TITLE
build of zgpu crashes on new version of zig

### ISSUE THREAD

**Issue by mifopen** [michal-z/zig-gamedev#82]
```
➜  zig build
./libs/zgpu/libs/mach-gpu-dawn/build.zig:1458:54: error: no member named 'iterate' in struct 'std.fs.Dir.OpenDirOptions'
    var dir = try std.fs.openDirAbsolute(abs_dir, .{ .iterate = true });
                                                     ^
```
works on `zig-macos-aarch64-0.10.0-dev.2751+08459ff1c`
crashes on `zig-macos-aarch64-0.10.0-dev.3027+0e26c6149`

The latest version of mach-gpu-dawn build uses
```zig
var dir = try std.fs.openIterableDirAbsolute(abs_dir, .{});
```

btw The readme.md tells us that
`Project requires Zig 0.10.0-dev.2412 (master) or newer to compile.`
but I'm wondering what should be the correct wording here. The language is quite unstable and it looks like we need the explicit latest working version number as well?

**Comment by kamidev** [comment]
I just sent a PR for this: https://github.com/michal-z/zig-gamedev/pull/83, let's see what @michal-z says.

**Comment by mifopen** [comment]
Although, I'm a little bit uncomfortable with having a "slightly modified" version of the external library in the project and not a properly updated one. It's interesting what @michal-z vision on that

**Comment by michal-z** [comment]
Thanks for report and for PR. zig-gamedev always tries to follow latest Zig compiler so I will merge @kamidev PR.
